config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :meta_items

  root 'products#index'
  devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :cart, only: [:show] do
  	# post "add", path: "add/:id"
  	post "add/:id", :as => "add", :action => "add"
  	get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end
end

app/models/meta_item.rb
class MetaItem < ApplicationRecord
	has_many :products
end

app/controllers/meta_items_controller.rb
class MetaItemsController < InheritedResources::Base
  before_action :set_meta_item, only: [:show, :edit, :update, :destroy]

  def index
  	@meta_items = MetaItem.all
  end

  def show
  	@products = @meta_item.products
  end

  def new
  	@meta_item = MetaItem.new
  end

  def edit
  end

  def create
  	@meta_item = MetaItem.new(meta_item_params)

  	respond_to do |format|
  		if @meta_item.save
  			format.html { redirect_to @meta_item, notice: "Categories was successfully created!" }
  			format.json { render :show, status: :created, location: @meta_item }
  		else
  			format.html { render new }
  			format.json { render json: @meta_item.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def update
  	respond_to do |format|
  		if @meta_item.update(meta_item_params)
  			format.html { redirect_to @meta_item, notice: "Categories was successfully updated!" }
  			format.json { render :show, status: :ok, location: @meta_item }
  		else
  			format.html { render :edit }
  			format.json { render json: @meta_item.errors, status: :unprocessable_entity }
  		end
  	end
  end

  def destroy
  	@meta_item.destroy
  	respond_to do |format|
  		format.html { redirect_to meta_items_url, notice: "Category was successfully destroyed!" }
  		format.json { head :no_content }
  	end
  end

  private
  	def set_meta_item
  		@meta_item = MetaItem.includes(:products).find(params[:id])
  	end

    def meta_item_params
      params.require(:meta_item).permit(:name, :sku, :price)
    end
end

app/helpers/meta_items_helper.rb
module MetaItemsHelper
end

app/views/meta_items/_form.html.erb
<%= form_for(meta_item) do |f| %>
  <% if meta_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meta_item.errors.count, "error") %> prohibited this meta_item from being saved:</h2>

      <ul>
      <% meta_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meta_items/edit.html.erb
<h1>Editing Meta Item</h1>

<%= render 'form', meta_item: @meta_item %>

<%= link_to 'Show', @meta_item %> |
<%= link_to 'Back', meta_items_path %>

app/views/meta_items/index.html.erb
<h3>Meta Items</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sku</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meta_items.each do |meta_item| %>
      <tr>
        <td><%= meta_item.name %></td>
        <td><%= meta_item.sku %></td>
        <td><%= link_to 'Show', meta_item %></td>
        <td><%= link_to 'Edit', edit_meta_item_path(meta_item) %></td>
        <td><%= link_to 'Destroy', meta_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meta Item', new_meta_item_path %>

app/views/meta_items/new.html.erb
<h1>New Meta Item</h1>

<%= render 'form', meta_item: @meta_item %>

<%= link_to 'Back', meta_items_path %>

app/views/meta_items/show.html.erb
<h1><%= @meta_item.name %></h1>

<ul>
	<li>
		<p>
  		<strong>Sku:</strong>
  		<%= @meta_item.sku %>
		</p>
	</li>
</ul>

<%= render "products/table", products: @products %>

<%= link_to 'Back', meta_items_path %>