config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :meta_items

  root 'products#index'
  devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :cart, only: [:show] do
  	# post "add", path: "add/:id"
  	post "add/:id", :as => "add", :action => "add"
  	get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end
end

app/models/cart.rb
class Cart
  attr_reader :items

  def self.build_from_hash hash
  	items = if hash["cart"] then
  	  hash["cart"]["items"].map do |item_data|
  	  	CartItem.new item_data["product_id"], item_data["quantity"]
  	  end
    else
    	[]
    end

    new items
  end

  def initialize items = []
  	@items = items
  end

  def add_item product_id
  	item = @items.find { |item| item.product_id == product_id }
  	if item
  		item.increment
  	else
  		@items << CartItem.new(product_id)
  	end
  end

  def empty?
  	@items.empty?
  end

  def count
  	@items.length
  end

  def serialize
  	items = @items.map do |item|
  		{
  			"product_id" => item.product_id,
  			"quantity" => item.quantity
  		}
  	end

  	{
  		"items" => items
  	}
  end

  def total_price
    @items.inject(0) { |sum, item| sum + item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_filter :initialize_cart

	def add
		@cart.add_item params[:id]
		session["cart"] = @cart.serialize
		product = Product.find params[:id]
		redirect_to :back, notice: "Added #{product.name} to cart."
	end

	def show
	end

	def checkout
		if current_user
			@order_form = OrderForm.new user: current_user
			@client_token = Braintree::ClientToken.generate
		else
			redirect_to new_user_session_url
		end
	end

	# def destroy
	# end
end

app/views/carts/_braintree.html.erb
<script>
braintree.setup("<%= @client_token %>", "dropin", {
  container: "payment-form"
});
</script>

app/views/carts/checkout.html.erb
<h3> Checkout </h3>

<h4> The follwing products checking out: </h4>

<!-- The list of cart items. -->
<ul>
	<% @cart.items.each do |item| %>
	  <li>
	  	<em><%= item.quantity %></em>
	  	<%= item.product.name %>
	  	<%= number_to_currency item.total_price  %>
	  </li>
	<% end %>
</ul>

<!-- The total price for cart. -->
<p>
	<strong>
		Total price:
		  <%= number_to_currency @cart.total_price %>
	</strong>
</p>

<div class="divider"></div>

<!-- The form for order. -->
<%= form_for @order_form, url: orders_path do |f| %>

	<%= render 'orders/errors' %>

	<div class="field">
		<%= f.fields_for :user, f.object.user do |u| %>
			<div class="form-group">
				<p>First Name</p>
				<%= u.text_field :first_name, placeholder: "First Name" %><br>
				<p>Last Name</p>
				<%= u.text_field :last_name,  placeholder: "Last Name" %><br>
				<p>Email</p>
				<%= u.text_field :email,      placeholder: "Email" %><br>
				<p>Phone</p>
				<%= u.text_field :phone, placeholder: "Phone" %><br>
				<span class="help-block">This will help you track your order more effectively.</span>
			</div>
			<div class="form-group .input-field">
				<p>Address</p>
				<%= u.text_field :address, placeholder: "Location(except from the country, state and city)" %><br>

				<p>Zip Code/Postal Code</p>
				<%= u.text_field :zip_code, placeholder: "Zipcode" %><br>

				<p>City</p>
				<%= u.text_field :city, placeholder: "City" %><br>

				<p>State</p>
				<%= u.text_field :state, placeholder: "State" %><br>

				<div class=".input-field">
					<p>Counrty</p>
					<%= u.country_select :country, { priority_countries: [ "TW", "US", "JP", "GB" ] }, :class => "browser-default" %>
				</div>
			</div>
		<% end %>
	</div>

	<br>
	<div class="divider"></div>

	<div class="payment">
		<!-- The form for payment. (Paypal, credit card, allpay, alipay) -->
		<h4>Choose your payment method:</h4>

		<div id="braintree">
			<a class="waves-effect waves-light btn">Braintree</a>
		</div>
		<br>
		<div id="payment-form" style="display: none"></div><br>

		<div id="alipay" >
			<div class="action">
				<script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-amount="<%= @cart.total_price * 100 %>" data-description="HappyCompany products order" data-key="<%= Rails.configuration.stripe[:publishable_key] %>"  data-name="Happy Company" data-label="Pay with Card or Alipay" data-locale="auto" data-alipay="true"></script>
			</div>
		</div>
	</div>

	<br>
	<div class="divider"></div>
	<br>

	<div class="actions">
		<%= f.submit 'Place order',:class => "btn waves-effect waves-light" %>
	</div>
<% end %>

<script>
	$(function(){
		$(".payment #braintree").on('click', function() {
			$("#payment-form").toggle(
				function(){
					$("#payment-form").html("<%= j render 'braintree' %>");
				}
			);
		});
	});
</script>

app/views/carts/show.html.erb
<h1> Current Cart List</h1>

<table>
	<thead>
		<tr>
			<th>Quantity</th>
			<th>Product</th>
			<th>Price</th>
		</tr>
	</thead>

	<% @cart.items.each do |item| %>
	  <tr>
	  	<td><%= item.quantity %></td>
	  	<td>
	  		<%= image_tag(item.product.image_groups.first.image.thumb) %>
	  		<%= link_to item.product.name, item.product %>
	  	</td>
			<td><%= item.total_price %></td>
	  </tr>
	<% end %>

	<tfoot>
		<tr>
			<td colspan="3">
				<strong>
					Total Price:
					  <%= number_to_currency @cart.total_price %>
				</strong>
			</th>
		</tr>
	</tfoot>
</table>

<p>Total price of your cart:</p>
<p><%= number_to_currency @cart.total_price %></p>

<p>
	<%= link_to "Checkout", checkout_cart_path %>
</p>