config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :meta_items

  root 'products#index'
  devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :cart, only: [:show] do
  	# post "add", path: "add/:id"
  	post "add/:id", :as => "add", :action => "add"
  	get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :find_meta_items

  def initialize_cart
  	@cart = Cart.build_from_hash session
  end

  def find_meta_items
  	@meta_items = MetaItem.all
  end

  def authenticate_admin!
  	authenticate_user!

  	unless current_user.admin?
  		redirect_to root_path, alert: "You are not allowed to do this operation!"
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_cart.html.erb
<% if @cart %>
	<% if @cart.empty? %>
		<li>Empty Cart</li>
	<% else %>
		<%= link_to "You have #{pluralize @cart.count, "items"}.", cart_path %>
	<% end %>
<% end %>

app/views/application/_nav.html.erb
<nav>
	<div class="nav-wrapper">
		<div class="col s12 left">
			<%= link_to "Happy Store", root_path, :class => "brand-logo left" %>

			<ul class="left" style="margin-left: 210px; line-height: 64px">
				<li><%= link_to "Products", products_path%></li>

				<li>
					<a class="dropdown-button" data-activates="dropdown-category">Category<i class="material-icons right">arrow_drop_down</i></a>
				</li>
			</ul>
		</div>

		<div class="col s12 right" >
			<ul style="margin-right: 20px; line-height: 64px;">
				<li style="margin-right: -10px;">
					<%= render 'cart' %>
				</li>

				<li>
					<a class="dropdown-button" href="#!" data-activates="dropdown-user"><i class="large material-icons">perm_identity</i></a>
				</li>
			</ul>
		</div>
	</div>
</nav>

<!-- Dropdwon Category Structure -->
<ul id="dropdown-category" class="dropdown-content">
	<% @meta_items.each do |m_item| %>
		<li><%= link_to m_item.name, m_item %></li>
	<% end %>
</ul>

<!-- Dropdown User Structure -->
<ul id="dropdown-user" class="dropdown-content">
	<li>
		<% if user_signed_in? %>
			<strong>Welcome <%= current_user.first_name %></strong>
			<%= link_to "Log out", destroy_user_session_path, method: :delete %>
		<% else %>
			<%= link_to "Log in", new_user_session_path %>
		<% end %>
	</li>
</ul>