config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :meta_items

  root 'products#index'
  devise_for :users
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :cart, only: [:show] do
  	# post "add", path: "add/:id"
  	post "add/:id", :as => "add", :action => "add"
  	get :checkout
  end

  resources :orders, only: [ :index, :show, :create, :update ] do
    member do
      get :new_payment
      post :pay
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :meta_item
	has_many :image_groups, dependent: :destroy

	accepts_nested_attributes_for :image_groups

	validates_presence_of :name, :description, :price
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
	before_action :set_product, only: [:show, :edit, :update, :destroy ]
	before_action :initialize_cart
	before_action :authenticate_admin!, only: [ :new, :edit, :update, :create, :destroy ]

	def index
		@products = Product.includes(:image_groups).all
	end

	def show
		@image = @product.image_groups.first.image
	end

	def new
		@product = Product.new
		@image_group = @product.image_groups.new
	end

	def edit
	end

	def create
		@product = Product.new(product_params)

		respond_to do |format|
			if @product.save
				format.html { redirect_to @product, notice: "Your product was successfully created!" }
				format.json { render :show, status: :created, location: @product }
			else
			  format.html { render :new }
			  format.json { render json: @product.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Your product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		@product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
	end

  private

    def set_product
  		@product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :active, :price, :meta_item_id, image_groups_attributes: [:image])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this @product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class=".input-field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="row">
    <div class=".input-field">
      <%= f.label :description %>
      <%= f.text_area :description, :class => "materialize-textarea" %>
    </div>
  </div>

  <div class="row">
    <div class=".input-field">
      <%= f.check_box :active, :id => "filled-in", :class => "filled-in" %>
      <%= f.label :active, :for => "filled-in" %>
    </div>
  </div>

  <div class="row">
    <div class=".input-field">
      <%= f.label :price %>
      <%= f.text_field :price %>
    </div>
  </div>

  <div class="row">
    <div class=".input-field">
      <%= f.fields_for :image_groups, @product.image_groups.first do |c| %>
        <%= c.file_field :image %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class=".input-field col s12">
      <%= f.label :meta_item %>
      <%= f.select :meta_item_id, MetaItem.all.map { |c| [c.name, c.id]},{}, :class => "browser-default" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Create Product',:class => "btn waves-effect waves-light" %>
  </div>
<% end %>

app/views/products/_table.html.erb
<% products.each do |product| %>
  <div class="row">
    <div class="col s12 m7">
      <div class="card small">
        <div class="card-image">
          <%= image_tag(product.image_groups.first.image.thumb) %>
          <span class="card-title"><%= link_to product.name, product %></span>
        </div>
        <div class="card-content">
          <p><%= product.description %> | <%= number_to_currency product.price %></p>
        </div>
        <div class="card-action">
          <% if current_user && current_user.admin? %>
            <%= link_to 'Edit', edit_product_path(product) %>
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          <div class="chip">
            <%= product.active %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @product, :class => "waves-effect waves-light btn" %> |
<%= link_to 'Back', products_path, :class => "waves-effect waves-light btn" %>

app/views/products/index.html.erb
<%= render "products/table", products: @products %>

<% if current_user && current_user.admin? %>
   <%= link_to 'New Product', new_product_path, :class => "waves-effect waves-light btn" %>
<% end %>

app/views/products/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', products_path, :class => "waves-effect waves-light btn" %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @product.active %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Pictures:</strong>
  <%= image_tag(@image.medium) %>
</p>

<p>
	<%= @product.meta_item.name %>
</p>

<%= link_to "Add to cart", add_cart_path, method: :post %>
<%= link_to 'Edit', edit_product_path(@product) %>
<%= link_to 'Back', products_path %>